server:
  port: 8092

spring:
  application:
    name: QUEUE-SERVICE
  datasource:
    url: jdbc:mysql://${HMS_DB_HOST:localhost}:3306/queue_db?useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${HMS_DB_USER:root}
    password: ${HMS_DB_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    enabled: false
    baseline-on-migrate: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://${HMS_DISCOVERY_HOST:localhost}:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
