package com.hms.reporting.service;

import com.hms.reporting.feign.*;
import com.lowagie.text.*;
import com.lowagie.text.pdf.PdfWriter;
import org.springframework.stereotype.Service;
import java.awt.Color;
import java.io.ByteArrayOutputStream;
import java.time.LocalDate;
import java.util.List;
import java.util.Map;
import java.util.HashMap;

@Service
public class ReportingService {

    private final AppointmentClient appointmentClient;
    private final PatientClient patientClient;
    private final BillingClient billingClient;
    private final DoctorClient doctorClient;
    private final PharmacyClient pharmacyClient;
    private final RecordsClient recordsClient;

    public ReportingService(
        AppointmentClient appointmentClient,
        PatientClient patientClient,
        BillingClient billingClient,
        DoctorClient doctorClient,
        PharmacyClient pharmacyClient,
        RecordsClient recordsClient
    ) {
        this.appointmentClient = appointmentClient;
        this.patientClient = patientClient;
        this.billingClient = billingClient;
        this.doctorClient = doctorClient;
        this.pharmacyClient = pharmacyClient;
        this.recordsClient = recordsClient;
    }

    public byte[] generatePrescriptionPdf(Long prescriptionId) {
        PrescriptionDto prescription = pharmacyClient.getById(prescriptionId);
        Map<String, Object> patient = patientClient.getPatientById(prescription.getPatientId());
        Map<String, Object> doctor = doctorClient.getDoctorById(prescription.getDoctorId());

        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        Document document = new Document(PageSize.A4);
        PdfWriter.getInstance(document, baos);

        document.open();
        
        // Header
        Font headerFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 18, Color.DARK_GRAY);
        Paragraph header = new Paragraph("CITY CARE HOSPITAL - DIGITAL PRESCRIPTION", headerFont);
        header.setAlignment(Element.ALIGN_CENTER);
        document.add(header);
        document.add(new Paragraph(" "));

        // Patient & Doctor Info
        Font labelFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 12);
        document.add(new Paragraph("Patient Name: " + patient.get("firstName") + " " + patient.get("lastName"), labelFont));
        document.add(new Paragraph("Doctor: " + doctor.get("fullName"), labelFont));
        document.add(new Paragraph("Date: " + prescription.getIssuedDate()));
        document.add(new Paragraph(" "));

        // Prescription Details
        Table table = new Table(2);
        table.addCell("Medication");
        table.addCell(prescription.getMedicationName());
        table.addCell("Dosage");
        table.addCell(prescription.getDose());
        table.addCell("Frequency");
        table.addCell(prescription.getFrequency());
        table.addCell("Duration");
        table.addCell(prescription.getDuration());
        table.addCell("Instructions");
        table.addCell(prescription.getInstructions());
        document.add(table);

        document.add(new Paragraph(" "));
        document.add(new Paragraph("Digitally generated by HMS Core - Valid without physical signature."));
        
        document.close();
        return baos.toByteArray();
    }

    public byte[] generateDischargeSummaryPdf(Long appointmentId) {
        VisitNoteDto note = recordsClient.getByAppointmentId(appointmentId);
        Map<String, Object> patient = patientClient.getPatientById(note.getPatientId());
        Map<String, Object> doctor = doctorClient.getDoctorById(note.getDoctorId());

        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        Document document = new Document(PageSize.A4);
        PdfWriter.getInstance(document, baos);

        document.open();
        
        Font headerFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 22, Color.BLUE);
        Paragraph header = new Paragraph("DISCHARGE SUMMARY", headerFont);
        header.setAlignment(Element.ALIGN_CENTER);
        document.add(header);
        document.add(new Paragraph(" "));

        document.add(new Paragraph("Patient: " + patient.get("firstName") + " " + patient.get("lastName")));
        document.add(new Paragraph("Treating Physician: " + doctor.get("fullName")));
        document.add(new Paragraph("Visit Date: " + note.getVisitDate()));
        document.add(new Paragraph(" "));

        addSection(document, "Subjective (History of Present Illness)", note.getSubjective());
        addSection(document, "Objective (Vitals & Observations)", note.getObjective());
        addSection(document, "Assessment (Diagnosis)", "ICD: " + note.getDiagnosisCode() + "\n" + note.getAssessment());
        addSection(document, "Plan & Follow-up Instructions", note.getPlan());

        document.close();
        return baos.toByteArray();
    }

    private void addSection(Document doc, String title, String content) {
        Font sectionFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 14);
        doc.add(new Paragraph(title, sectionFont));
        doc.add(new Paragraph(content != null ? content : "No data documented."));
        doc.add(new Paragraph(" "));
    }

    public Map<String, Object> dashboardSummary() {
        List<Map<String, Object>> apps = appointmentClient.getAllAppointments();
        List<Map<String, Object>> invoices = billingClient.getAllInvoices();
        
        String today = LocalDate.now().toString();
        
        long todayAptCount = apps.stream()
            .filter(a -> today.equals(a.get("appointmentDate")))
            .count();
            
        double todayRev = invoices.stream()
            .filter(i -> "PAID".equals(i.get("status")) && today.equals(i.get("paidAt") != null ? i.get("paidAt").toString() : ""))
            .mapToDouble(i -> ((Number) i.get("totalAmount")).doubleValue())
            .sum();

        return Map.of(
            "totalPatients", safeSize(patientClient.getAllPatients()),
            "activeDoctors", safeSize(doctorClient.getAllDoctors()),
            "todayAppointments", todayAptCount,
            "todayRevenue", todayRev
        );
    }

    public Map<String, Object> departmentLoad() { 
        List<Map<String, Object>> apps = appointmentClient.getAllAppointments();
        String today = LocalDate.now().toString();
        
        long opd = apps.stream().filter(a -> today.equals(a.get("appointmentDate")) && "OPD".equals(a.get("type"))).count();
        long tele = apps.stream().filter(a -> today.equals(a.get("appointmentDate")) && "TELEMEDICINE".equals(a.get("type"))).count();
        long emergency = apps.stream().filter(a -> today.equals(a.get("appointmentDate")) && "EMERGENCY".equals(a.get("type"))).count();

        // Simulated capacity %
        return Map.of(
            "OPD", Math.min(100, (int)(opd * 10)), 
            "Telemedicine", Math.min(100, (int)(tele * 15)),
            "Emergency", Math.min(100, (int)(emergency * 25)),
            "Laboratory", 45 // Stub for lab load
        ); 
    }

    public Map<String, Object> exportReport(String reportType, String format) {
        String fileName = reportType.toUpperCase() + "_" + LocalDate.now() + "." + format.toLowerCase();
        Map<String, Object> meta = new HashMap<>();
        meta.put("reportName", fileName);
        meta.put("generatedAt", LocalDate.now().toString());
        meta.put("status", "SUCCESS");
        return meta;
    }

    public List<Map<String, Object>> doctorPerformance() { 
        List<Map<String, Object>> doctors = doctorClient.getAllDoctors();
        return doctors.stream().map(d -> {
            Map<String, Object> perf = new HashMap<>();
            perf.put("id", d.get("id"));
            perf.put("name", d.get("fullName"));
            perf.put("rating", d.get("rating") != null ? d.get("rating") : 4.5);
            perf.put("patients", (int)(Math.random() * 100)); // Simulated volume for now
            return perf;
        }).limit(5).toList();
    }

    public Map<String, Object> appointmentVolume(String range) {
        // Return 7 days of simulated volume for Chart.js
        Map<String, Object> data = new HashMap<>();
        for (int i = 6; i >= 0; i--) {
            data.put(LocalDate.now().minusDays(i).toString(), (int)(Math.random() * 20) + 5);
        }
        return data;
    }

    public Map<String, Object> revenue(String from, String to, String groupBy) {
        // Return 7 days of simulated revenue for Chart.js
        Map<String, Object> data = new HashMap<>();
        for (int i = 6; i >= 0; i--) {
            data.put(LocalDate.now().minusDays(i).toString(), (int)(Math.random() * 5000) + 1000);
        }
        return data;
    }

    public Map<String, Object> patientVolume(String range) { return Map.of("range", range, "count", safeSize(patientClient.getAllPatients())); }
    public Map<String, Object> doctorPerformanceById(Long doctorId) { return Map.of("doctorId", doctorId, "rating", 4.8); }
    public Map<String, Object> diagnosesHeatmap(String month) { return Map.of("month", month != null ? month : "current", "data", List.of()); }

    private int safeSize(List<?> data) {
        return data == null ? 0 : data.size();
    }
}
