server:
  port: 8761

spring:
  application:
    name: DISCOVERY-SERVICE

eureka:
  client:
    register-with-eureka: false   # Don't register itself as a client
    fetch-registry: false         # Don't fetch registry from anywhere
