import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { BillingApiService, Invoice } from './billing-api.service';
import { AuthService } from '../../core/auth.service';

@Component({
  selector: 'app-billing',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule],
  template: `
    <div class="container">
      <div class="hero">
        <div>
          <h2>Billing</h2>
          <p class="subtitle">Invoice generation, tracking, and payment control center.</p>
        </div>
        <div class="pill">Revenue Ops</div>
      </div>

      <div class="success" *ngIf="successMessage" role="status" aria-live="polite">{{ successMessage }}</div>

      <form [formGroup]="form" (ngSubmit)="createInvoice()" class="section card" aria-labelledby="create-invoice-heading" *ngIf="!isPatientRole">
        <h3 id="create-invoice-heading">Create Invoice</h3>
        <input type="number" formControlName="patientId" placeholder="Patient ID" />
        <input type="number" formControlName="totalAmount" placeholder="Total amount" />
        <button type="submit" [disabled]="form.invalid || creatingInvoice">{{ creatingInvoice ? 'Creating…' : 'Create Invoice' }}</button>
      </form>

      <section class="section card" *ngIf="isPatientRole">
        <h3>Billing Access</h3>
        <div class="empty">Invoices are generated by hospital billing desk. You can only view and pay your own invoices.</div>
      </section>

      <section class="section card" aria-labelledby="invoice-list-heading">
        <h3 id="invoice-list-heading">Invoice List</h3>
        <button type="button" (click)="loadInvoices()" [disabled]="form.controls.patientId.invalid || loadingInvoices" aria-label="Load invoice list for entered patient">{{ loadingInvoices ? 'Loading…' : (isPatientRole ? 'Load My Invoices' : 'Load Invoices') }}</button>

        <div class="loading-text" *ngIf="loadingInvoices" role="status" aria-live="polite">Fetching invoice timeline…</div>

        <ul class="list" *ngIf="!loadingInvoices && invoices.length > 0">
          <li *ngFor="let inv of invoices">
            <div class="row-head">
              <strong>{{ inv.invoiceNumber }} — ₹{{ inv.totalAmount }}</strong>
              <span class="status" [class.paid]="inv.status === 'PAID'">{{ inv.status }}</span>
            </div>
            <span>{{ inv.claimStatus }} · {{ inv.sourceSummary || 'Generated from billing flow' }}</span>
            <span class="sub" *ngIf="inv.invoiceDate">Issued on {{ inv.invoiceDate }}</span>
            <button type="button" *ngIf="inv.id && inv.status !== 'PAID'" (click)="pay(inv.id)" [disabled]="payingInvoiceId === inv.id" [attr.aria-label]="'Mark invoice ' + inv.invoiceNumber + ' as paid'">
              {{ payingInvoiceId === inv.id ? 'Updating…' : 'Mark Paid' }}
            </button>
          </li>
        </ul>

        <div class="empty" *ngIf="!loadingInvoices && invoices.length === 0">No invoices loaded for this patient yet.</div>
      </section>
    </div>
  `,
  styles: [`
    .hero { display: flex; justify-content: space-between; gap: 1rem; align-items: flex-start; }
    .subtitle { margin-top: 0.45rem; color: var(--text-soft); }
    .pill { border: 1px solid rgba(0,212,170,0.45); color: var(--primary); background: rgba(0,212,170,0.12); border-radius: 999px; padding: 0.35rem 0.75rem; font-size: 0.78rem; text-transform: uppercase; letter-spacing: 0.04em; font-weight: 700; white-space: nowrap; }
    .success { margin-top: 1rem; border: 1px solid rgba(34,197,94,0.45); background: rgba(34,197,94,0.12); color: #80e8a6; border-radius: 10px; padding: 0.65rem 0.8rem; }
    .card { border: 1px solid var(--border); border-radius: 14px; padding: 0.9rem; background: linear-gradient(180deg, rgba(26,39,64,0.65), rgba(15,23,38,0.95)); }
    .section { margin-top: 1.2rem; display: grid; gap: 0.6rem; }
    .list { list-style: none; padding: 0; margin: 0; }
    .list li { border: 1px solid var(--border); border-radius: 10px; padding: 0.75rem; margin-bottom: 0.5rem; display: grid; gap: 0.35rem; background: rgba(11,18,32,0.55); }
    .list span { color: var(--text-soft); }
    .sub { font-size: 0.8rem; color: var(--text-muted); }
    .row-head { display: flex; justify-content: space-between; gap: 0.8rem; align-items: center; }
    .status { border: 1px solid rgba(246,178,63,0.5); color: #ffd58d; background: rgba(246,178,63,0.12); border-radius: 999px; padding: 0.2rem 0.56rem; font-size: 0.72rem; text-transform: uppercase; letter-spacing: 0.04em; font-weight: 700; }
    .status.paid { border-color: rgba(34,197,94,0.45); color: #80e8a6; background: rgba(34,197,94,0.12); }
    .empty { color: var(--text-muted); font-size: 0.88rem; }

    @media (max-width: 760px) {
      .hero { flex-direction: column; }
      .row-head { flex-direction: column; align-items: flex-start; }
      .list li button { width: 100%; }
    }
  `]
})
export class BillingComponent implements OnInit {
  invoices: Invoice[] = [];
  loadingInvoices = false;
  creatingInvoice = false;
  payingInvoiceId: number | null = null;
  successMessage = '';
  isPatientRole = false;

  readonly form = this.fb.nonNullable.group({
    patientId: [0, [Validators.required, Validators.min(1)]],
    totalAmount: [0, [Validators.required, Validators.min(1)]]
  });

  constructor(
    private fb: FormBuilder,
    private billingApi: BillingApiService,
    private authService: AuthService
  ) {}

  ngOnInit(): void {
    this.isPatientRole = (this.authService.getRole() ?? '').toUpperCase() === 'PATIENT';
    if (this.isPatientRole) {
      const userId = this.authService.getUserId() ?? 0;
      this.form.controls.patientId.setValue(userId > 0 ? userId : 0);
    }
  }

  createInvoice(): void {
    if (this.isPatientRole) {
      this.successMessage = 'Invoice creation is restricted. Please contact hospital billing desk.';
      return;
    }

    if (this.form.invalid) return;

    this.creatingInvoice = true;
    this.successMessage = '';

    this.billingApi.createInvoice(this.form.getRawValue()).subscribe({
      next: () => {
        this.successMessage = 'Invoice created successfully.';
        this.creatingInvoice = false;
        this.loadInvoices();
      },
      error: () => {
        this.creatingInvoice = false;
      }
    });
  }

  loadInvoices(): void {
    const patientId = this.isPatientRole
      ? (this.authService.getUserId() ?? 0)
      : this.form.controls.patientId.value;
    if (!patientId || patientId < 1) return;

    this.loadingInvoices = true;

    this.billingApi.getInvoicesByPatient(patientId).subscribe({
      next: items => {
        this.invoices = items;
        this.loadingInvoices = false;
      },
      error: () => {
        this.invoices = [];
        this.loadingInvoices = false;
      }
    });
  }

  pay(invoiceId: number): void {
    this.payingInvoiceId = invoiceId;
    this.successMessage = '';

    this.billingApi.payInvoice(invoiceId).subscribe({
      next: () => {
        this.successMessage = `Invoice #${invoiceId} marked as paid.`;
        this.payingInvoiceId = null;
        this.loadInvoices();
      },
      error: () => {
        this.payingInvoiceId = null;
      }
    });
  }
}
